# Generated by Django 5.2 on 2025-04-06 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=150)),
                ('senha', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identificacao_unica', models.TextField(max_length=9)),
                ('titulo', models.TextField(max_length=300)),
                ('proposta', models.TextField(max_length=3000)),
                ('curso', models.TextField(max_length=150)),
                ('coordenador', models.TextField(max_length=150)),
                ('ch_total', models.IntegerField()),
                ('ch_semanal_docente', models.IntegerField()),
                ('ch_semanal_estudante', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('instagram', models.TextField(blank=True)),
                ('contato', models.TextField()),
                ('formulario', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='dias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('turno', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('lugar', models.TextField(max_length=300)),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalExtensaoUnicap_app.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area', models.TextField(max_length=150)),
                ('id_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalExtensaoUnicap_app.projeto')),
            ],
        ),
    ]
